# Generated by Django 5.0.2 on 2025-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(choices=[('KM', 'Kumbh Mela'), ('BD', 'Badrinath'), ('JG', 'Jagannath Yatra'), ('UJ', 'Ujjain'), ('KD', 'Kedarnath Mandir')], max_length=2)),
                ('end_location', models.CharField(choices=[('KM', 'Kumbh Mela'), ('BD', 'Badrinath'), ('JG', 'Jagannath Yatra'), ('UJ', 'Ujjain'), ('KD', 'Kedarnath Mandir')], max_length=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('number_of_passengers', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
