# Generated by Django 5.0.2 on 2025-05-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='start_location',
            field=models.CharField(max_length=100),
        ),
    ]
